### PR TITLE
[xfce] adding x11-themes/greybird x11-themes/numix-icon

### PR DESCRIPTION
**Pull request by mudler**

### CODE REVIEW

**Comment by Enlik** [comment]
Do you know if x11-themes/gnome-themes-standard is still needed? Almost 7 MB!

/usr/lib32/gtk-2.0/2.10.0/engines/libadwaita.so
/usr/share/themes/Adwaita/...
/usr/share/themes/HighContrast/...
/usr/share/icons/HighContrast/...
/usr/share/doc/gnome-themes-standard-*/...
/usr/lib64/gtk-2.0/2.10.0/engines/libadwaita.so

**Comment by mudler** [comment]
Actually, i think we can drop it

**Comment by Enlik** [comment]
Introduced by     [Xfce] add x11-themes/gnome-themes-standard, makes Rigo look nice
OTOH, in KDE:   [KDE] Drop gnome-themes-common: oxygen-gtk no longer borks Rigo
(-common is a typo, should be -standard).

So the main question actually is: does Rigo look good on default Xfce without it? If yes, drop, if not, leave. (It would be wrong to have the "official GUI" look bad!)

**Comment by mudler** [comment]
I just tested and i didn't noticed nothing really different

**Pull request merged**
