### PR TITLE
New ISO Build Script & Gnome Forensics Review

### PR DESCRIPTION
**Pull request by geaaru**

### CODE REVIEW

**Comment by wolfden** [comment]
all of this is missing https://github.com/Sabayon/molecules/tree/master/remaster/gforensic 
and I believe also missing
https://github.com/Sabayon/molecules/blob/master/scripts/xfce_remaster_post.sh

**Comment by wolfden** [comment]
Is https://github.com/Sabayon/molecules/blob/master/molecules/forensicxfce.common still being used?
following seem to have been ignored
# List of packages that would be removed from chrooted system (comma separated )
packages_to_remove:
	x11-wm/fluxbox,
	games-misc/cowsay,
        games-action/minetest_game

**Comment by geaaru** [comment]
Hi, packages_to_remove are now under forensics.common:

https://github.com/geaaru/molecules/blob/master/molecules/forensic.common

and included on renamed spec files:

https://github.com/geaaru/molecules/blob/master/molecules/sabayon-amd64-gnome-forensics.spec

All rows that I delete from forensics.common are already included with same values from gnome.common:

https://github.com/Sabayon/molecules/pull/12/commits/69efe9a15aa593ee89abf95667b08d7220447d74

Take a look on log of task 6394357274533224876 I see that try to remove fluxbox but is not installed.

Can you try to check logfile of task and said me where could be the error?

**Comment by wolfden** [comment]
Thanks for pointing out where stuff is at now.

I took a look at the log but see no errors I see stuff called, so I don't know what to think at this moment 

> >> [ChrootHandler|sabayon-amd64-gnome-forensics.spec] executing post_run
>> [ChrootHandler|sabayon-amd64-gnome-forensics.spec] spawning: /sabayon/scripts/remaster_post.sh /sabayon/scripts/xfce_remaster_post.sh
Umounting bind to /var/cache/molecule/moleculeRY3EE2chroot/root/var/lib/entropy/client/packages
>> [ChrootHandler|sabayon-amd64-gnome-forensics.spec] executing kill
>>  (3/4) [Runner|sabayon-amd64-gnome-forensics.spec] executing <class 'molecule.specs.plugins.remaster_plugin.CdrootHandler'>
>> [CdrootHandler|sabayon-amd64-gnome-forensics.spec] executing pre_run
>> [CdrootHandler|sabayon-amd64-gnome-forensics.spec] preparing environment
>> [CdrootHandler|sabayon-amd64-gnome-forensics.spec] compressing chroot
>> [CdrootHandler|sabayon-amd64-gnome-forensics.spec] spawning: /usr/bin/mksquashfs /var/cache/molecule/moleculeRY3EE2chroot/root /var/cache/molecule/moleculeRY3EE2chroot/cdroot/livecd.squashfs -noappend -no-progress -comp xz
Parallel mksquashfs: Using 8 processors
Creating 4.0 filesystem on /var/cache/molecule/moleculeRY3EE2chroot/cdroot/livecd.squashfs, block size 131072.

**Comment by wolfden** [comment]
Think I figured out the issue with why minetest was still on the iso, cowsay was removed so that is working properly.

Just need to get the gforensic directory stuff to move over and it will be all good

**Comment by geaaru** [comment]
Yeah, it strange that gforensic directory is not present soon. From log seems that script start correctly. I will try to add some debug message/commands.

**Comment by wolfden** [comment]
Today's new iso, same issue - nothing is moving over

**Comment by wolfden** [comment]
So, out of curiosity I tried to build a local spin on my home machine and ran into this:

> cp: cannot stat '/home/gru/spin/files/usr/share/backgrounds/sabayon-forensic.png': No such file or directory
cp: cannot stat '/home/gru/spin/files/usr/share/backgrounds/sabayon-forensic.jpg': No such file or directory
cp: cannot stat '/home/gru/spin/files/usr/share/backgrounds/kgdm.jpg': No such file or directory
cp: cannot stat '/home/gru/spin/files/files/org.freedesktop.udisks.policy': No such file or directory
cp: cannot stat '/home/gru/spin/files/files/org.freedesktop.udisks2.policy': No such file or directory
cp: cannot stat '/home/gru/spin/files/files/theme.lua': No such file or directory
cp: cannot stat '/home/gru/spin/files/files/Qogir-dark': No such file or directory
cp: cannot stat '/home/gru/spin/files/files/forensic-desktops/*': No such file or directory
cp: cannot stat '/home/gru/spin/files/files/org.sabayon.gschema.override': No such file or directory
cp: cannot stat '/home/gru/spin/files/files/org.gnome.shell.extensions.dash-to-dock.gschema.xml': No such file or directory

> gru@dispicable-me ~/scripts $ ls -la /home/gru/spin/files/usr/share/backgrounds/
total 848
drwxr-xr-x 1 gru gru     96 Aug 11 00:50 .
drwxr-xr-x 1 gru gru     22 Aug 11 00:50 ..
-rw-r--r-- 1 gru gru 116075 Aug 11 00:50 kgdm.jpg
-rw-r--r-- 1 gru gru 301955 Aug 11 00:50 sabayon-forensic.jpg
-rw-r--r-- 1 gru gru 443456 Aug 11 00:50 sabayon-forensic.png

The files are all there, so it seems an issue with molecule program itself?  Otherwise the build went fine.  Maybe makes sense to you?

**Comment by wolfden** [comment]
Successfully building the iso here locally, just a few customization issues is all.  I am using my 4 original files to build it.

I have lost access to the log file from the server.  It appears the whole log directory changes out with each build.  So I am trying to remember, but I don't remember this error:

`cp: cannot create regular file '/var/tmp/molecule7f1fzg74chroot/root/etc/xdg/awesome/themes/default/theme.lua': No such file or directory`

This error should be occurring and appearing in the cloud log file, plus the cp -v option is not showing up in the cloud log, but it appears here on my local build.

`'/home/gru/spin/files/usr/share/backgrounds/sabayonlinux.png' -> '/var/tmp/molecule7f1fzg74chroot/root/usr/share/backgrounds/sabayonlinux.png'`

So my guess is, the server is not executing the post_master_sh file properly.

**Pull request merged**
